# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: batch_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='batch_message.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x62\x61tch_message.proto\x12\x0f\x61nantak.message\"\x93\x03\n\x0c\x42\x61tchMessage\x12\x11\n\ttugger_id\x18\x01 \x01(\t\x12\x13\n\x0boperator_id\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61rt_ids\x18\x0b \x03(\t\x12\x18\n\x10\x63urrent_location\x18\x15 \x01(\t\x12\x0f\n\x07item_id\x18\x16 \x01(\t\x12\x10\n\x08quantity\x18\x17 \x01(\x05\x12\x13\n\x0b\x63\x61rt_number\x18\x18 \x01(\x05\x12\x15\n\rcart_position\x18\x19 \x01(\t\x12\x15\n\rdelay_seconds\x18\x1a \x01(\x05\x12\x15\n\rnext_location\x18\x1b \x01(\t\x12\x10\n\x08\x64istance\x18\x1f \x01(\t\x12\r\n\x05speed\x18  \x01(\t\x12\x0c\n\x04stop\x18! \x01(\t\x12\r\n\x05start\x18\" \x01(\t\x12\x14\n\x0c\x63urr_command\x18) \x01(\t\x12\x1a\n\x12\x63urr_command_ts_us\x18* \x01(\x03\x12\x14\n\x0clast_command\x18+ \x01(\t\x12\x1a\n\x12last_command_ts_us\x18, \x01(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATCHMESSAGE = _descriptor.Descriptor(
  name='BatchMessage',
  full_name='anantak.message.BatchMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tugger_id', full_name='anantak.message.BatchMessage.tugger_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator_id', full_name='anantak.message.BatchMessage.operator_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='anantak.message.BatchMessage.batch_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cart_ids', full_name='anantak.message.BatchMessage.cart_ids', index=3,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_location', full_name='anantak.message.BatchMessage.current_location', index=4,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='anantak.message.BatchMessage.item_id', index=5,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='anantak.message.BatchMessage.quantity', index=6,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cart_number', full_name='anantak.message.BatchMessage.cart_number', index=7,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cart_position', full_name='anantak.message.BatchMessage.cart_position', index=8,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delay_seconds', full_name='anantak.message.BatchMessage.delay_seconds', index=9,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_location', full_name='anantak.message.BatchMessage.next_location', index=10,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='anantak.message.BatchMessage.distance', index=11,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='anantak.message.BatchMessage.speed', index=12,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='anantak.message.BatchMessage.stop', index=13,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='anantak.message.BatchMessage.start', index=14,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curr_command', full_name='anantak.message.BatchMessage.curr_command', index=15,
      number=41, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curr_command_ts_us', full_name='anantak.message.BatchMessage.curr_command_ts_us', index=16,
      number=42, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_command', full_name='anantak.message.BatchMessage.last_command', index=17,
      number=43, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_command_ts_us', full_name='anantak.message.BatchMessage.last_command_ts_us', index=18,
      number=44, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=444,
)

DESCRIPTOR.message_types_by_name['BatchMessage'] = _BATCHMESSAGE

BatchMessage = _reflection.GeneratedProtocolMessageType('BatchMessage', (_message.Message,), dict(
  DESCRIPTOR = _BATCHMESSAGE,
  __module__ = 'batch_message_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.BatchMessage)
  ))
_sym_db.RegisterMessage(BatchMessage)


# @@protoc_insertion_point(module_scope)
