# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_open_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='can_open_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63\x61n_open_messages.proto\x12\x0f\x61nantak.message\"\xb9\x02\n\x0fSteeringMessage\x12\x18\n\x10motor_is_engaged\x18\n \x01(\x05\x12\x1c\n\x14\x63ontrol_target_angle\x18\x14 \x01(\x02\x12\x19\n\x11motor_status_word\x18\x1e \x01(\x05\x12\x1a\n\x12motor_target_angle\x18\x1f \x01(\x02\x12\x1b\n\x13motor_current_angle\x18  \x01(\x02\x12\x1d\n\x15motor_target_velocity\x18! \x01(\x02\x12\x1e\n\x16motor_current_velocity\x18\" \x01(\x02\x12\x1a\n\x12motor_target_accel\x18# \x01(\x02\x12\x1a\n\x12motor_target_decel\x18$ \x01(\x02\x12\x0f\n\x07\x63ommand\x18\x32 \x01(\t\x12\x12\n\nerror_code\x18\x64 \x01(\x05\"\xc2\x03\n\x0fTractionMessage\x12\x1b\n\x13traction_is_engaged\x18\n \x01(\x05\x12\x1d\n\x15traction_target_speed\x18\x14 \x01(\x05\x12\x18\n\x10traction_horn_on\x18\x1e \x01(\x05\x12\x1c\n\x14traction_status_word\x18( \x01(\x05\x12\x1d\n\x15traction_velocity_mps\x18) \x01(\x02\x12\x1d\n\x15traction_tiller_state\x18* \x01(\r\x12!\n\x19traction_throttle_voltage\x18+ \x01(\x02\x12\x1f\n\x17traction_manual_horn_on\x18, \x01(\r\x12\x1a\n\x12traction_turtle_on\x18- \x01(\r\x12\x1d\n\x15traction_nudge_fwd_on\x18. \x01(\r\x12\x1d\n\x15traction_nudge_rev_on\x18/ \x01(\r\x12\x17\n\x0ftraction_ksi_on\x18\x30 \x01(\r\x12!\n\x19traction_encoder_position\x18\x31 \x01(\r\x12\x0f\n\x07\x63ommand\x18< \x01(\t\x12\x12\n\nerror_code\x18\x64 \x01(\x05'
)




_STEERINGMESSAGE = _descriptor.Descriptor(
  name='SteeringMessage',
  full_name='anantak.message.SteeringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_is_engaged', full_name='anantak.message.SteeringMessage.motor_is_engaged', index=0,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_target_angle', full_name='anantak.message.SteeringMessage.control_target_angle', index=1,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_status_word', full_name='anantak.message.SteeringMessage.motor_status_word', index=2,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_target_angle', full_name='anantak.message.SteeringMessage.motor_target_angle', index=3,
      number=31, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_current_angle', full_name='anantak.message.SteeringMessage.motor_current_angle', index=4,
      number=32, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_target_velocity', full_name='anantak.message.SteeringMessage.motor_target_velocity', index=5,
      number=33, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_current_velocity', full_name='anantak.message.SteeringMessage.motor_current_velocity', index=6,
      number=34, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_target_accel', full_name='anantak.message.SteeringMessage.motor_target_accel', index=7,
      number=35, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_target_decel', full_name='anantak.message.SteeringMessage.motor_target_decel', index=8,
      number=36, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='anantak.message.SteeringMessage.command', index=9,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='anantak.message.SteeringMessage.error_code', index=10,
      number=100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=358,
)


_TRACTIONMESSAGE = _descriptor.Descriptor(
  name='TractionMessage',
  full_name='anantak.message.TractionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='traction_is_engaged', full_name='anantak.message.TractionMessage.traction_is_engaged', index=0,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_target_speed', full_name='anantak.message.TractionMessage.traction_target_speed', index=1,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_horn_on', full_name='anantak.message.TractionMessage.traction_horn_on', index=2,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_status_word', full_name='anantak.message.TractionMessage.traction_status_word', index=3,
      number=40, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_velocity_mps', full_name='anantak.message.TractionMessage.traction_velocity_mps', index=4,
      number=41, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_tiller_state', full_name='anantak.message.TractionMessage.traction_tiller_state', index=5,
      number=42, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_throttle_voltage', full_name='anantak.message.TractionMessage.traction_throttle_voltage', index=6,
      number=43, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_manual_horn_on', full_name='anantak.message.TractionMessage.traction_manual_horn_on', index=7,
      number=44, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_turtle_on', full_name='anantak.message.TractionMessage.traction_turtle_on', index=8,
      number=45, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_nudge_fwd_on', full_name='anantak.message.TractionMessage.traction_nudge_fwd_on', index=9,
      number=46, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_nudge_rev_on', full_name='anantak.message.TractionMessage.traction_nudge_rev_on', index=10,
      number=47, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_ksi_on', full_name='anantak.message.TractionMessage.traction_ksi_on', index=11,
      number=48, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traction_encoder_position', full_name='anantak.message.TractionMessage.traction_encoder_position', index=12,
      number=49, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='anantak.message.TractionMessage.command', index=13,
      number=60, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='anantak.message.TractionMessage.error_code', index=14,
      number=100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=811,
)

DESCRIPTOR.message_types_by_name['SteeringMessage'] = _STEERINGMESSAGE
DESCRIPTOR.message_types_by_name['TractionMessage'] = _TRACTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SteeringMessage = _reflection.GeneratedProtocolMessageType('SteeringMessage', (_message.Message,), {
  'DESCRIPTOR' : _STEERINGMESSAGE,
  '__module__' : 'can_open_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.SteeringMessage)
  })
_sym_db.RegisterMessage(SteeringMessage)

TractionMessage = _reflection.GeneratedProtocolMessageType('TractionMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRACTIONMESSAGE,
  '__module__' : 'can_open_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.TractionMessage)
  })
_sym_db.RegisterMessage(TractionMessage)


# @@protoc_insertion_point(module_scope)
