# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='component_config.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63omponent_config.proto\x12\x0f\x61nantak.message\"\xaa\x05\n\x0f\x43omponentConfig\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x16\n\x0epublisher_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63ommander_name\x18\x03 \x01(\t\x12\x13\n\x0bstatus_name\x18\x04 \x01(\t\x12\x17\n\x0f\x63ycle_frequency\x18\n \x01(\x02\x12\x17\n\x0f\x63onfig_filename\x18\x0b \x01(\t\x12\x1e\n\x16max_iteration_interval\x18\x0c \x01(\x03\x12!\n\x19max_observation_frequency\x18\r \x01(\x02\x12\x18\n\x10recycle_interval\x18\x0e \x01(\x03\x12\x1f\n\x17interval_to_empty_queue\x18\x0f \x01(\x05\x12J\n\x10observation_type\x18\x14 \x03(\x0b\x32\x30.anantak.message.ComponentConfig.ObservationType\x12\x37\n\x06sensor\x18\x1e \x03(\x0b\x32\'.anantak.message.ComponentConfig.Sensor\x12K\n\x11status_reply_type\x18( \x03(\x0b\x32\x30.anantak.message.ComponentConfig.StatusReplyType\x1aO\n\x0fObservationType\x12\x17\n\x0fsubscriber_name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x15\n\rmax_frequency\x18\x03 \x01(\x02\x1a.\n\x06Sensor\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x16\n\x0epublisher_name\x18\x02 \x02(\t\x1a\x41\n\x0fStatusReplyType\x12\x17\n\x0fsubscriber_name\x18\x01 \x02(\t\x12\x15\n\rmax_frequency\x18\x03 \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPONENTCONFIG_OBSERVATIONTYPE = _descriptor.Descriptor(
  name='ObservationType',
  full_name='anantak.message.ComponentConfig.ObservationType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_name', full_name='anantak.message.ComponentConfig.ObservationType.subscriber_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='anantak.message.ComponentConfig.ObservationType.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_frequency', full_name='anantak.message.ComponentConfig.ObservationType.max_frequency', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=611,
)

_COMPONENTCONFIG_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='anantak.message.ComponentConfig.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.message.ComponentConfig.Sensor.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publisher_name', full_name='anantak.message.ComponentConfig.Sensor.publisher_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=659,
)

_COMPONENTCONFIG_STATUSREPLYTYPE = _descriptor.Descriptor(
  name='StatusReplyType',
  full_name='anantak.message.ComponentConfig.StatusReplyType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_name', full_name='anantak.message.ComponentConfig.StatusReplyType.subscriber_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_frequency', full_name='anantak.message.ComponentConfig.StatusReplyType.max_frequency', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=726,
)

_COMPONENTCONFIG = _descriptor.Descriptor(
  name='ComponentConfig',
  full_name='anantak.message.ComponentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.message.ComponentConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publisher_name', full_name='anantak.message.ComponentConfig.publisher_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commander_name', full_name='anantak.message.ComponentConfig.commander_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_name', full_name='anantak.message.ComponentConfig.status_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycle_frequency', full_name='anantak.message.ComponentConfig.cycle_frequency', index=4,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_filename', full_name='anantak.message.ComponentConfig.config_filename', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_iteration_interval', full_name='anantak.message.ComponentConfig.max_iteration_interval', index=6,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_observation_frequency', full_name='anantak.message.ComponentConfig.max_observation_frequency', index=7,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recycle_interval', full_name='anantak.message.ComponentConfig.recycle_interval', index=8,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval_to_empty_queue', full_name='anantak.message.ComponentConfig.interval_to_empty_queue', index=9,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='observation_type', full_name='anantak.message.ComponentConfig.observation_type', index=10,
      number=20, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='anantak.message.ComponentConfig.sensor', index=11,
      number=30, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_reply_type', full_name='anantak.message.ComponentConfig.status_reply_type', index=12,
      number=40, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMPONENTCONFIG_OBSERVATIONTYPE, _COMPONENTCONFIG_SENSOR, _COMPONENTCONFIG_STATUSREPLYTYPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=726,
)

_COMPONENTCONFIG_OBSERVATIONTYPE.containing_type = _COMPONENTCONFIG
_COMPONENTCONFIG_SENSOR.containing_type = _COMPONENTCONFIG
_COMPONENTCONFIG_STATUSREPLYTYPE.containing_type = _COMPONENTCONFIG
_COMPONENTCONFIG.fields_by_name['observation_type'].message_type = _COMPONENTCONFIG_OBSERVATIONTYPE
_COMPONENTCONFIG.fields_by_name['sensor'].message_type = _COMPONENTCONFIG_SENSOR
_COMPONENTCONFIG.fields_by_name['status_reply_type'].message_type = _COMPONENTCONFIG_STATUSREPLYTYPE
DESCRIPTOR.message_types_by_name['ComponentConfig'] = _COMPONENTCONFIG

ComponentConfig = _reflection.GeneratedProtocolMessageType('ComponentConfig', (_message.Message,), dict(

  ObservationType = _reflection.GeneratedProtocolMessageType('ObservationType', (_message.Message,), dict(
    DESCRIPTOR = _COMPONENTCONFIG_OBSERVATIONTYPE,
    __module__ = 'component_config_pb2'
    # @@protoc_insertion_point(class_scope:anantak.message.ComponentConfig.ObservationType)
    ))
  ,

  Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
    DESCRIPTOR = _COMPONENTCONFIG_SENSOR,
    __module__ = 'component_config_pb2'
    # @@protoc_insertion_point(class_scope:anantak.message.ComponentConfig.Sensor)
    ))
  ,

  StatusReplyType = _reflection.GeneratedProtocolMessageType('StatusReplyType', (_message.Message,), dict(
    DESCRIPTOR = _COMPONENTCONFIG_STATUSREPLYTYPE,
    __module__ = 'component_config_pb2'
    # @@protoc_insertion_point(class_scope:anantak.message.ComponentConfig.StatusReplyType)
    ))
  ,
  DESCRIPTOR = _COMPONENTCONFIG,
  __module__ = 'component_config_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.ComponentConfig)
  ))
_sym_db.RegisterMessage(ComponentConfig)
_sym_db.RegisterMessage(ComponentConfig.ObservationType)
_sym_db.RegisterMessage(ComponentConfig.Sensor)
_sym_db.RegisterMessage(ComponentConfig.StatusReplyType)


# @@protoc_insertion_point(module_scope)
