# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnoser_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diagnoser_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x64iagnoser_messages.proto\x12\x0f\x61nantak.message\"\xbe\x03\n\x10\x44iagnoserMessage\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x65rror_timestamp\x18\x03 \x01(\x03\x12\x13\n\x0bline_number\x18\x04 \x01(\x05\x12\x12\n\nowner_name\x18\x05 \x01(\t\x12\x1e\n\x16incremental_num_counts\x18\x06 \x01(\x05\x12\x10\n\x08severity\x18\x07 \x01(\x05\x12\x14\n\x0c\x65rror_number\x18\x08 \x01(\t\x12\x12\n\nmachine_id\x18\t \x01(\t\x12\x32\n\x07\x63ommand\x18\x64 \x01(\x0b\x32!.anantak.message.DiagnoserCommand\x12\x34\n\x08response\x18\x65 \x01(\x0b\x32\".anantak.message.DiagnoserResponse\x12=\n\rinput_request\x18\x66 \x01(\x0b\x32&.anantak.message.DiagnoserInputRequest\x12?\n\x0einput_response\x18g \x01(\x0b\x32\'.anantak.message.DiagnoserInputResponse\"\x86\x01\n\x10\x44iagnoserCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x03(\t\x12\x13\n\x0bworking_dir\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x03(\t\x12\x13\n\x0bscript_name\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"\x95\x01\n\x11\x44iagnoserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x10\n\x08resolved\x18\x04 \x01(\t\x12\x17\n\x0fstart_timestamp\x18\x05 \x01(\x03\x12\x15\n\rend_timestamp\x18\x06 \x01(\x03\x12\x0e\n\x06\x61\x63tion\x18\x07 \x01(\t\"_\n\x15\x44iagnoserInputRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\ninput_type\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"@\n\x16\x44iagnoserInputResponse\x12\x13\n\x0binput_value\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03'
)




_DIAGNOSERMESSAGE = _descriptor.Descriptor(
  name='DiagnoserMessage',
  full_name='anantak.message.DiagnoserMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='anantak.message.DiagnoserMessage.unique_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='anantak.message.DiagnoserMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_timestamp', full_name='anantak.message.DiagnoserMessage.error_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='anantak.message.DiagnoserMessage.line_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_name', full_name='anantak.message.DiagnoserMessage.owner_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incremental_num_counts', full_name='anantak.message.DiagnoserMessage.incremental_num_counts', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='anantak.message.DiagnoserMessage.severity', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_number', full_name='anantak.message.DiagnoserMessage.error_number', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='anantak.message.DiagnoserMessage.machine_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='anantak.message.DiagnoserMessage.command', index=9,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='anantak.message.DiagnoserMessage.response', index=10,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_request', full_name='anantak.message.DiagnoserMessage.input_request', index=11,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_response', full_name='anantak.message.DiagnoserMessage.input_response', index=12,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=492,
)


_DIAGNOSERCOMMAND = _descriptor.Descriptor(
  name='DiagnoserCommand',
  full_name='anantak.message.DiagnoserCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='anantak.message.DiagnoserCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='working_dir', full_name='anantak.message.DiagnoserCommand.working_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='anantak.message.DiagnoserCommand.parameters', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='script_name', full_name='anantak.message.DiagnoserCommand.script_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='anantak.message.DiagnoserCommand.category', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='anantak.message.DiagnoserCommand.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=629,
)


_DIAGNOSERRESPONSE = _descriptor.Descriptor(
  name='DiagnoserResponse',
  full_name='anantak.message.DiagnoserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='anantak.message.DiagnoserResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='anantak.message.DiagnoserResponse.stdout', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='anantak.message.DiagnoserResponse.stderr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolved', full_name='anantak.message.DiagnoserResponse.resolved', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='anantak.message.DiagnoserResponse.start_timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='anantak.message.DiagnoserResponse.end_timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='anantak.message.DiagnoserResponse.action', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=781,
)


_DIAGNOSERINPUTREQUEST = _descriptor.Descriptor(
  name='DiagnoserInputRequest',
  full_name='anantak.message.DiagnoserInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prompt', full_name='anantak.message.DiagnoserInputRequest.prompt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='anantak.message.DiagnoserInputRequest.input_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='anantak.message.DiagnoserInputRequest.options', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='anantak.message.DiagnoserInputRequest.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=783,
  serialized_end=878,
)


_DIAGNOSERINPUTRESPONSE = _descriptor.Descriptor(
  name='DiagnoserInputResponse',
  full_name='anantak.message.DiagnoserInputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_value', full_name='anantak.message.DiagnoserInputResponse.input_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='anantak.message.DiagnoserInputResponse.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=880,
  serialized_end=944,
)

_DIAGNOSERMESSAGE.fields_by_name['command'].message_type = _DIAGNOSERCOMMAND
_DIAGNOSERMESSAGE.fields_by_name['response'].message_type = _DIAGNOSERRESPONSE
_DIAGNOSERMESSAGE.fields_by_name['input_request'].message_type = _DIAGNOSERINPUTREQUEST
_DIAGNOSERMESSAGE.fields_by_name['input_response'].message_type = _DIAGNOSERINPUTRESPONSE
DESCRIPTOR.message_types_by_name['DiagnoserMessage'] = _DIAGNOSERMESSAGE
DESCRIPTOR.message_types_by_name['DiagnoserCommand'] = _DIAGNOSERCOMMAND
DESCRIPTOR.message_types_by_name['DiagnoserResponse'] = _DIAGNOSERRESPONSE
DESCRIPTOR.message_types_by_name['DiagnoserInputRequest'] = _DIAGNOSERINPUTREQUEST
DESCRIPTOR.message_types_by_name['DiagnoserInputResponse'] = _DIAGNOSERINPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiagnoserMessage = _reflection.GeneratedProtocolMessageType('DiagnoserMessage', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSERMESSAGE,
  '__module__' : 'diagnoser_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.DiagnoserMessage)
  })
_sym_db.RegisterMessage(DiagnoserMessage)

DiagnoserCommand = _reflection.GeneratedProtocolMessageType('DiagnoserCommand', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSERCOMMAND,
  '__module__' : 'diagnoser_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.DiagnoserCommand)
  })
_sym_db.RegisterMessage(DiagnoserCommand)

DiagnoserResponse = _reflection.GeneratedProtocolMessageType('DiagnoserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSERRESPONSE,
  '__module__' : 'diagnoser_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.DiagnoserResponse)
  })
_sym_db.RegisterMessage(DiagnoserResponse)

DiagnoserInputRequest = _reflection.GeneratedProtocolMessageType('DiagnoserInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSERINPUTREQUEST,
  '__module__' : 'diagnoser_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.DiagnoserInputRequest)
  })
_sym_db.RegisterMessage(DiagnoserInputRequest)

DiagnoserInputResponse = _reflection.GeneratedProtocolMessageType('DiagnoserInputResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSERINPUTRESPONSE,
  '__module__' : 'diagnoser_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.DiagnoserInputResponse)
  })
_sym_db.RegisterMessage(DiagnoserInputResponse)


# @@protoc_insertion_point(module_scope)
