# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='error_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x65rror_messages.proto\x12\x0f\x61nantak.message\"\xc7\x01\n\x14\x45rrorsRequestMessage\x12\x19\n\nfull_state\x18\n \x01(\x08:\x05\x66\x61lse\x12\x13\n\x0bstart_ts_us\x18\x0b \x01(\x03\x12\x1a\n\x12min_severity_level\x18\x14 \x01(\x05\x12\x1a\n\x12max_severity_level\x18\x15 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x32 \x01(\t\x12\x1a\n\x12\x63ommand_str_params\x18\x33 \x03(\t\x12\x1a\n\x12\x63ommand_int_params\x18\x34 \x03(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ERRORSREQUESTMESSAGE = _descriptor.Descriptor(
  name='ErrorsRequestMessage',
  full_name='anantak.message.ErrorsRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_state', full_name='anantak.message.ErrorsRequestMessage.full_state', index=0,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_ts_us', full_name='anantak.message.ErrorsRequestMessage.start_ts_us', index=1,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_severity_level', full_name='anantak.message.ErrorsRequestMessage.min_severity_level', index=2,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_severity_level', full_name='anantak.message.ErrorsRequestMessage.max_severity_level', index=3,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='anantak.message.ErrorsRequestMessage.command', index=4,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_str_params', full_name='anantak.message.ErrorsRequestMessage.command_str_params', index=5,
      number=51, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_int_params', full_name='anantak.message.ErrorsRequestMessage.command_int_params', index=6,
      number=52, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=241,
)

DESCRIPTOR.message_types_by_name['ErrorsRequestMessage'] = _ERRORSREQUESTMESSAGE

ErrorsRequestMessage = _reflection.GeneratedProtocolMessageType('ErrorsRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _ERRORSREQUESTMESSAGE,
  __module__ = 'error_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.ErrorsRequestMessage)
  ))
_sym_db.RegisterMessage(ErrorsRequestMessage)


# @@protoc_insertion_point(module_scope)
