# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x66ile_messages.proto\x12\x0f\x61nantak.message\"\x85\x01\n\x12\x46ileRequestMessage\x12\x10\n\x08\x66ilepath\x18\n \x02(\t\x12?\n\x0b\x63ompression\x18\x0b \x02(\x0e\x32$.anantak.message.FileCompressionType:\x04\x41UTO\x12\x1c\n\x0esend_in_chunks\x18\x0c \x02(\x08:\x04true\"\x8d\x02\n\x13\x46ileResponseMessage\x12\x10\n\x08\x66ilepath\x18\n \x02(\t\x12\x10\n\x08\x66ilesize\x18\x0b \x02(\x03\x12/\n\x06result\x18\x0c \x02(\x0e\x32\x1f.anantak.message.FileResultType\x12\x12\n\nnum_chunks\x18\r \x02(\x05\x12\x12\n\nchunk_size\x18\x0e \x02(\x05\x12\x17\n\x0flast_chunk_size\x18\x0f \x02(\x05\x12\x39\n\x0b\x63ompression\x18\x10 \x02(\x0e\x32$.anantak.message.FileCompressionType\x12\x17\n\x0ftransmission_id\x18\x14 \x02(\x03\x12\x0c\n\x04\x64\x61ta\x18\x1e \x01(\x0c\"Z\n\x16\x46ileDataRequestMessage\x12\x13\n\x0b\x63hunk_index\x18\r \x02(\x05\x12\x12\n\nnum_chunks\x18\x0e \x02(\x05\x12\x17\n\x0ftransmission_id\x18\x14 \x02(\x03\"\x91\x01\n\x17\x46ileDataResponseMessage\x12\x0c\n\x04\x64\x61ta\x18\n \x02(\x0c\x12\x13\n\x0b\x62ytes_start\x18\x0b \x02(\x03\x12\x11\n\tnum_bytes\x18\x0c \x02(\x03\x12\x13\n\x0b\x63hunk_index\x18\r \x02(\x05\x12\x12\n\nnum_chunks\x18\x0e \x02(\x05\x12\x17\n\x0ftransmission_id\x18\x14 \x02(\x03\"\xfb\x01\n\x0b\x46ileMessage\x12\x34\n\x07request\x18\n \x01(\x0b\x32#.anantak.message.FileRequestMessage\x12\x36\n\x08response\x18\x14 \x01(\x0b\x32$.anantak.message.FileResponseMessage\x12=\n\x0c\x64\x61ta_request\x18\x1e \x01(\x0b\x32\'.anantak.message.FileDataRequestMessage\x12?\n\rdata_response\x18( \x01(\x0b\x32(.anantak.message.FileDataResponseMessage*6\n\x13\x46ileCompressionType\x12\x08\n\x04\x41UTO\x10\x00\x12\x07\n\x03ZIP\x10\x01\x12\x0c\n\x08ORIGINAL\x10\x02*Y\n\x0e\x46ileResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\x12\n\x0e\x46ILE_NOT_FOUND\x10\x01\x12\x11\n\rFILE_NOT_READ\x10\x02\x12\x13\n\x0f\x46ILE_IS_TOO_BIG\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FILECOMPRESSIONTYPE = _descriptor.EnumDescriptor(
  name='FileCompressionType',
  full_name='anantak.message.FileCompressionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZIP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORIGINAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=942,
  serialized_end=996,
)
_sym_db.RegisterEnumDescriptor(_FILECOMPRESSIONTYPE)

FileCompressionType = enum_type_wrapper.EnumTypeWrapper(_FILECOMPRESSIONTYPE)
_FILERESULTTYPE = _descriptor.EnumDescriptor(
  name='FileResultType',
  full_name='anantak.message.FileResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE_NOT_FOUND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE_NOT_READ', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE_IS_TOO_BIG', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=998,
  serialized_end=1087,
)
_sym_db.RegisterEnumDescriptor(_FILERESULTTYPE)

FileResultType = enum_type_wrapper.EnumTypeWrapper(_FILERESULTTYPE)
AUTO = 0
ZIP = 1
ORIGINAL = 2
SUCCESS = 0
FILE_NOT_FOUND = 1
FILE_NOT_READ = 2
FILE_IS_TOO_BIG = 3



_FILEREQUESTMESSAGE = _descriptor.Descriptor(
  name='FileRequestMessage',
  full_name='anantak.message.FileRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='anantak.message.FileRequestMessage.filepath', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compression', full_name='anantak.message.FileRequestMessage.compression', index=1,
      number=11, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send_in_chunks', full_name='anantak.message.FileRequestMessage.send_in_chunks', index=2,
      number=12, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=174,
)


_FILERESPONSEMESSAGE = _descriptor.Descriptor(
  name='FileResponseMessage',
  full_name='anantak.message.FileResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='anantak.message.FileResponseMessage.filepath', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filesize', full_name='anantak.message.FileResponseMessage.filesize', index=1,
      number=11, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='anantak.message.FileResponseMessage.result', index=2,
      number=12, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_chunks', full_name='anantak.message.FileResponseMessage.num_chunks', index=3,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='anantak.message.FileResponseMessage.chunk_size', index=4,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_chunk_size', full_name='anantak.message.FileResponseMessage.last_chunk_size', index=5,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compression', full_name='anantak.message.FileResponseMessage.compression', index=6,
      number=16, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmission_id', full_name='anantak.message.FileResponseMessage.transmission_id', index=7,
      number=20, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='anantak.message.FileResponseMessage.data', index=8,
      number=30, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=446,
)


_FILEDATAREQUESTMESSAGE = _descriptor.Descriptor(
  name='FileDataRequestMessage',
  full_name='anantak.message.FileDataRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk_index', full_name='anantak.message.FileDataRequestMessage.chunk_index', index=0,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_chunks', full_name='anantak.message.FileDataRequestMessage.num_chunks', index=1,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmission_id', full_name='anantak.message.FileDataRequestMessage.transmission_id', index=2,
      number=20, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=538,
)


_FILEDATARESPONSEMESSAGE = _descriptor.Descriptor(
  name='FileDataResponseMessage',
  full_name='anantak.message.FileDataResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='anantak.message.FileDataResponseMessage.data', index=0,
      number=10, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_start', full_name='anantak.message.FileDataResponseMessage.bytes_start', index=1,
      number=11, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_bytes', full_name='anantak.message.FileDataResponseMessage.num_bytes', index=2,
      number=12, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunk_index', full_name='anantak.message.FileDataResponseMessage.chunk_index', index=3,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_chunks', full_name='anantak.message.FileDataResponseMessage.num_chunks', index=4,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmission_id', full_name='anantak.message.FileDataResponseMessage.transmission_id', index=5,
      number=20, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=686,
)


_FILEMESSAGE = _descriptor.Descriptor(
  name='FileMessage',
  full_name='anantak.message.FileMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='anantak.message.FileMessage.request', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='anantak.message.FileMessage.response', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_request', full_name='anantak.message.FileMessage.data_request', index=2,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_response', full_name='anantak.message.FileMessage.data_response', index=3,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=940,
)

_FILEREQUESTMESSAGE.fields_by_name['compression'].enum_type = _FILECOMPRESSIONTYPE
_FILERESPONSEMESSAGE.fields_by_name['result'].enum_type = _FILERESULTTYPE
_FILERESPONSEMESSAGE.fields_by_name['compression'].enum_type = _FILECOMPRESSIONTYPE
_FILEMESSAGE.fields_by_name['request'].message_type = _FILEREQUESTMESSAGE
_FILEMESSAGE.fields_by_name['response'].message_type = _FILERESPONSEMESSAGE
_FILEMESSAGE.fields_by_name['data_request'].message_type = _FILEDATAREQUESTMESSAGE
_FILEMESSAGE.fields_by_name['data_response'].message_type = _FILEDATARESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['FileRequestMessage'] = _FILEREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['FileResponseMessage'] = _FILERESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['FileDataRequestMessage'] = _FILEDATAREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['FileDataResponseMessage'] = _FILEDATARESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['FileMessage'] = _FILEMESSAGE
DESCRIPTOR.enum_types_by_name['FileCompressionType'] = _FILECOMPRESSIONTYPE
DESCRIPTOR.enum_types_by_name['FileResultType'] = _FILERESULTTYPE

FileRequestMessage = _reflection.GeneratedProtocolMessageType('FileRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILEREQUESTMESSAGE,
  __module__ = 'file_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.FileRequestMessage)
  ))
_sym_db.RegisterMessage(FileRequestMessage)

FileResponseMessage = _reflection.GeneratedProtocolMessageType('FileResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILERESPONSEMESSAGE,
  __module__ = 'file_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.FileResponseMessage)
  ))
_sym_db.RegisterMessage(FileResponseMessage)

FileDataRequestMessage = _reflection.GeneratedProtocolMessageType('FileDataRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILEDATAREQUESTMESSAGE,
  __module__ = 'file_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.FileDataRequestMessage)
  ))
_sym_db.RegisterMessage(FileDataRequestMessage)

FileDataResponseMessage = _reflection.GeneratedProtocolMessageType('FileDataResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILEDATARESPONSEMESSAGE,
  __module__ = 'file_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.FileDataResponseMessage)
  ))
_sym_db.RegisterMessage(FileDataResponseMessage)

FileMessage = _reflection.GeneratedProtocolMessageType('FileMessage', (_message.Message,), dict(
  DESCRIPTOR = _FILEMESSAGE,
  __module__ = 'file_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.FileMessage)
  ))
_sym_db.RegisterMessage(FileMessage)


# @@protoc_insertion_point(module_scope)
