# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IoT_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IoT_messages.proto',
  package='anantak.Iot_message',
  syntax='proto2',
  serialized_pb=_b('\n\x12IoT_messages.proto\x12\x13\x61nantak.Iot_message\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x03\n\x04task\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32&.anantak.Iot_message.task.taskTypeEnum\x12\x36\n\x05state\x18\x03 \x01(\x0e\x32\'.anantak.Iot_message.task.taskStateEnum\x12\x10\n\x08progress\x18\x04 \x01(\x02\x12<\n\x08worksite\x18\x05 \x01(\x0b\x32*.anantak.Iot_message.task.worksiteMesssage\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x1a\x41\n\x10worksiteMesssage\x12\x0c\n\x04site\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01z\x18\x04 \x01(\x05\">\n\x0ctaskTypeEnum\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07TRANSIT\x10\x01\x12\n\n\x06PICKUP\x10\x02\x12\x0b\n\x07\x44ROPOFF\x10\x03\"?\n\rtaskStateEnum\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07WORKING\x10\x01\x12\x0b\n\x07\x42LOCKED\x10\x02\x12\n\n\x06UNABLE\x10\x03\"\xc6\x02\n\x1amachineStationRelationship\x12X\n\rrelativeState\x18\x01 \x01(\x0e\x32\x41.anantak.Iot_message.machineStationRelationship.relativeStateEnum\x12\x1f\n\x17\x61rrivalDepartureSeconds\x18\x02 \x01(\x02\x12\x17\n\x0fmachineIdentity\x18\x03 \x01(\t\"\x93\x01\n\x11relativeStateEnum\x12\x0c\n\x08INACTIVE\x10\x00\x12\x0f\n\x0b\x41PPROACHING\x10\x01\x12\r\n\tDEPARTING\x10\x02\x12\x0b\n\x07\x42LOCKED\x10\x03\x12\x0b\n\x07WAITING\x10\x04\x12\x08\n\x04OPEN\x10\x05\x12\n\n\x06\x43LOSED\x10\x06\x12\n\n\x06HAZARD\x10\x07\x12\t\n\x05MISC1\x10\x08\x12\t\n\x05MISC2\x10\t\"\x1a\n\x07marquee\x12\x0f\n\x07message\x18\x01 \x01(\t\"o\n\x1astationMachineRelationship\x12\x19\n\x11iotDeviceIdentity\x18\x01 \x01(\t\"6\n\x0fiotCommandsEnum\x12\x0b\n\x07\x46ORWARD\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x0c\n\x08NEXTCART\x10\x02')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TASK_TASKTYPEENUM = _descriptor.EnumDescriptor(
  name='taskTypeEnum',
  full_name='anantak.Iot_message.task.taskTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PICKUP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DROPOFF', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=410,
  serialized_end=472,
)
_sym_db.RegisterEnumDescriptor(_TASK_TASKTYPEENUM)

_TASK_TASKSTATEENUM = _descriptor.EnumDescriptor(
  name='taskStateEnum',
  full_name='anantak.Iot_message.task.taskStateEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCKED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNABLE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=474,
  serialized_end=537,
)
_sym_db.RegisterEnumDescriptor(_TASK_TASKSTATEENUM)

_MACHINESTATIONRELATIONSHIP_RELATIVESTATEENUM = _descriptor.EnumDescriptor(
  name='relativeStateEnum',
  full_name='anantak.Iot_message.machineStationRelationship.relativeStateEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPROACHING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEPARTING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCKED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAZARD', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC1', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC2', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=719,
  serialized_end=866,
)
_sym_db.RegisterEnumDescriptor(_MACHINESTATIONRELATIONSHIP_RELATIVESTATEENUM)

_STATIONMACHINERELATIONSHIP_IOTCOMMANDSENUM = _descriptor.EnumDescriptor(
  name='iotCommandsEnum',
  full_name='anantak.Iot_message.stationMachineRelationship.iotCommandsEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEXTCART', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=953,
  serialized_end=1007,
)
_sym_db.RegisterEnumDescriptor(_STATIONMACHINERELATIONSHIP_IOTCOMMANDSENUM)


_TASK_WORKSITEMESSSAGE = _descriptor.Descriptor(
  name='worksiteMesssage',
  full_name='anantak.Iot_message.task.worksiteMesssage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site', full_name='anantak.Iot_message.task.worksiteMesssage.site', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='anantak.Iot_message.task.worksiteMesssage.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='anantak.Iot_message.task.worksiteMesssage.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='anantak.Iot_message.task.worksiteMesssage.z', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=408,
)

_TASK = _descriptor.Descriptor(
  name='task',
  full_name='anantak.Iot_message.task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='anantak.Iot_message.task.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='anantak.Iot_message.task.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='anantak.Iot_message.task.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='anantak.Iot_message.task.progress', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worksite', full_name='anantak.Iot_message.task.worksite', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='anantak.Iot_message.task.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASK_WORKSITEMESSSAGE, ],
  enum_types=[
    _TASK_TASKTYPEENUM,
    _TASK_TASKSTATEENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=537,
)


_MACHINESTATIONRELATIONSHIP = _descriptor.Descriptor(
  name='machineStationRelationship',
  full_name='anantak.Iot_message.machineStationRelationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relativeState', full_name='anantak.Iot_message.machineStationRelationship.relativeState', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arrivalDepartureSeconds', full_name='anantak.Iot_message.machineStationRelationship.arrivalDepartureSeconds', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='machineIdentity', full_name='anantak.Iot_message.machineStationRelationship.machineIdentity', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MACHINESTATIONRELATIONSHIP_RELATIVESTATEENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=866,
)


_MARQUEE = _descriptor.Descriptor(
  name='marquee',
  full_name='anantak.Iot_message.marquee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='anantak.Iot_message.marquee.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=868,
  serialized_end=894,
)


_STATIONMACHINERELATIONSHIP = _descriptor.Descriptor(
  name='stationMachineRelationship',
  full_name='anantak.Iot_message.stationMachineRelationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iotDeviceIdentity', full_name='anantak.Iot_message.stationMachineRelationship.iotDeviceIdentity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATIONMACHINERELATIONSHIP_IOTCOMMANDSENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=896,
  serialized_end=1007,
)

_TASK_WORKSITEMESSSAGE.containing_type = _TASK
_TASK.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TASK.fields_by_name['type'].enum_type = _TASK_TASKTYPEENUM
_TASK.fields_by_name['state'].enum_type = _TASK_TASKSTATEENUM
_TASK.fields_by_name['worksite'].message_type = _TASK_WORKSITEMESSSAGE
_TASK_TASKTYPEENUM.containing_type = _TASK
_TASK_TASKSTATEENUM.containing_type = _TASK
_MACHINESTATIONRELATIONSHIP.fields_by_name['relativeState'].enum_type = _MACHINESTATIONRELATIONSHIP_RELATIVESTATEENUM
_MACHINESTATIONRELATIONSHIP_RELATIVESTATEENUM.containing_type = _MACHINESTATIONRELATIONSHIP
_STATIONMACHINERELATIONSHIP_IOTCOMMANDSENUM.containing_type = _STATIONMACHINERELATIONSHIP
DESCRIPTOR.message_types_by_name['task'] = _TASK
DESCRIPTOR.message_types_by_name['machineStationRelationship'] = _MACHINESTATIONRELATIONSHIP
DESCRIPTOR.message_types_by_name['marquee'] = _MARQUEE
DESCRIPTOR.message_types_by_name['stationMachineRelationship'] = _STATIONMACHINERELATIONSHIP

task = _reflection.GeneratedProtocolMessageType('task', (_message.Message,), dict(

  worksiteMesssage = _reflection.GeneratedProtocolMessageType('worksiteMesssage', (_message.Message,), dict(
    DESCRIPTOR = _TASK_WORKSITEMESSSAGE,
    __module__ = 'IoT_messages_pb2'
    # @@protoc_insertion_point(class_scope:anantak.Iot_message.task.worksiteMesssage)
    ))
  ,
  DESCRIPTOR = _TASK,
  __module__ = 'IoT_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.Iot_message.task)
  ))
_sym_db.RegisterMessage(task)
_sym_db.RegisterMessage(task.worksiteMesssage)

machineStationRelationship = _reflection.GeneratedProtocolMessageType('machineStationRelationship', (_message.Message,), dict(
  DESCRIPTOR = _MACHINESTATIONRELATIONSHIP,
  __module__ = 'IoT_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.Iot_message.machineStationRelationship)
  ))
_sym_db.RegisterMessage(machineStationRelationship)

marquee = _reflection.GeneratedProtocolMessageType('marquee', (_message.Message,), dict(
  DESCRIPTOR = _MARQUEE,
  __module__ = 'IoT_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.Iot_message.marquee)
  ))
_sym_db.RegisterMessage(marquee)

stationMachineRelationship = _reflection.GeneratedProtocolMessageType('stationMachineRelationship', (_message.Message,), dict(
  DESCRIPTOR = _STATIONMACHINERELATIONSHIP,
  __module__ = 'IoT_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.Iot_message.stationMachineRelationship)
  ))
_sym_db.RegisterMessage(stationMachineRelationship)


# @@protoc_insertion_point(module_scope)
