# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jira_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jira_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13jira_messages.proto\x12\x0f\x61nantak.message\"m\n\x12JiraRequestMessage\x12\x14\n\x0ctimestamp_us\x18\n \x01(\x03\x12\x1b\n\x13\x65xpiry_timestamp_us\x18\x0b \x01(\x03\x12$\n\x1cget_jira_tickets_for_machine\x18\x0c \x01(\x08\"f\n\x0bJiraMessage\x12\x14\n\x0ctimestamp_us\x18\n \x01(\x03\x12\x1b\n\x13\x65xpiry_timestamp_us\x18\x0b \x01(\x03\x12$\n\x1cget_jira_tickets_for_machine\x18\x0c \x01(\x08'
)




_JIRAREQUESTMESSAGE = _descriptor.Descriptor(
  name='JiraRequestMessage',
  full_name='anantak.message.JiraRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='anantak.message.JiraRequestMessage.timestamp_us', index=0,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiry_timestamp_us', full_name='anantak.message.JiraRequestMessage.expiry_timestamp_us', index=1,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_jira_tickets_for_machine', full_name='anantak.message.JiraRequestMessage.get_jira_tickets_for_machine', index=2,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=149,
)


_JIRAMESSAGE = _descriptor.Descriptor(
  name='JiraMessage',
  full_name='anantak.message.JiraMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='anantak.message.JiraMessage.timestamp_us', index=0,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiry_timestamp_us', full_name='anantak.message.JiraMessage.expiry_timestamp_us', index=1,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_jira_tickets_for_machine', full_name='anantak.message.JiraMessage.get_jira_tickets_for_machine', index=2,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['JiraRequestMessage'] = _JIRAREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['JiraMessage'] = _JIRAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JiraRequestMessage = _reflection.GeneratedProtocolMessageType('JiraRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _JIRAREQUESTMESSAGE,
  '__module__' : 'jira_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.JiraRequestMessage)
  })
_sym_db.RegisterMessage(JiraRequestMessage)

JiraMessage = _reflection.GeneratedProtocolMessageType('JiraMessage', (_message.Message,), {
  'DESCRIPTOR' : _JIRAMESSAGE,
  '__module__' : 'jira_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.JiraMessage)
  })
_sym_db.RegisterMessage(JiraMessage)


# @@protoc_insertion_point(module_scope)
