# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: machine_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='machine_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16machine_messages.proto\x12\x0f\x61nantak.message\"\xfd\x02\n\x1aMachineMeasurementsMessage\x12\x16\n\x0etyre_0_reading\x18\x64 \x01(\x02\x12\x16\n\x0etyre_1_reading\x18\x65 \x01(\x02\x12\x1f\n\x17steering_position_input\x18\x66 \x01(\x02\x12\x1b\n\x13speed_voltage_input\x18g \x01(\x02\x12\x15\n\rinhibit_state\x18h \x01(\x05\x12\x16\n\x0e\x63harging_state\x18i \x01(\x05\x12\x18\n\x10speed_mode_state\x18j \x01(\x05\x12!\n\x19steering_position_reading\x18k \x01(\x02\x12!\n\x19steering_velocity_reading\x18l \x01(\x02\x12 \n\x18\x63onsumed_current_reading\x18m \x01(\x02\x12\x1f\n\x17\x62\x61ttery_voltage_reading\x18n \x01(\x02\x12\x1f\n\x17\x62\x61ttery_current_reading\x18o \x01(\x02\"\xbf\x02\n\x16MachineControlsMessage\x12\x17\n\x0evoltage_output\x18\xc8\x01 \x01(\x02\x12\"\n\x19\x61uto_manual_control_state\x18\xc9\x01 \x01(\x05\x12\x1e\n\x15inhibit_control_state\x18\xca\x01 \x01(\x05\x12\x1f\n\x16inhibit2_control_state\x18\xcb\x01 \x01(\x05\x12!\n\x18speed_mode_control_state\x18\xcc\x01 \x01(\x05\x12!\n\x18steering_position_output\x18\xcd\x01 \x01(\x05\x12 \n\x17steering_engaged_output\x18\xce\x01 \x01(\x05\x12\x1f\n\x16ignition_control_state\x18\xcf\x01 \x01(\x05\x12\x1e\n\x15ignition_switch_state\x18\xd0\x01 \x01(\x05\"Y\n\x15MachineSignalsMessage\x12\x1d\n\x14speed_voltage_signal\x18\xac\x02 \x01(\x02\x12!\n\x18steering_position_signal\x18\xad\x02 \x01(\x02\"\xd2\x01\n\x16MachineReadingsMessage\x12\x42\n\x0cmeasurements\x18\xe8\x07 \x01(\x0b\x32+.anantak.message.MachineMeasurementsMessage\x12:\n\x08\x63ontrols\x18\xcc\x08 \x01(\x0b\x32\'.anantak.message.MachineControlsMessage\x12\x38\n\x07signals\x18\xb0\t \x01(\x0b\x32&.anantak.message.MachineSignalsMessage'
)




_MACHINEMEASUREMENTSMESSAGE = _descriptor.Descriptor(
  name='MachineMeasurementsMessage',
  full_name='anantak.message.MachineMeasurementsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tyre_0_reading', full_name='anantak.message.MachineMeasurementsMessage.tyre_0_reading', index=0,
      number=100, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tyre_1_reading', full_name='anantak.message.MachineMeasurementsMessage.tyre_1_reading', index=1,
      number=101, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_position_input', full_name='anantak.message.MachineMeasurementsMessage.steering_position_input', index=2,
      number=102, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_voltage_input', full_name='anantak.message.MachineMeasurementsMessage.speed_voltage_input', index=3,
      number=103, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inhibit_state', full_name='anantak.message.MachineMeasurementsMessage.inhibit_state', index=4,
      number=104, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='charging_state', full_name='anantak.message.MachineMeasurementsMessage.charging_state', index=5,
      number=105, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_mode_state', full_name='anantak.message.MachineMeasurementsMessage.speed_mode_state', index=6,
      number=106, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_position_reading', full_name='anantak.message.MachineMeasurementsMessage.steering_position_reading', index=7,
      number=107, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_velocity_reading', full_name='anantak.message.MachineMeasurementsMessage.steering_velocity_reading', index=8,
      number=108, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consumed_current_reading', full_name='anantak.message.MachineMeasurementsMessage.consumed_current_reading', index=9,
      number=109, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_voltage_reading', full_name='anantak.message.MachineMeasurementsMessage.battery_voltage_reading', index=10,
      number=110, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_current_reading', full_name='anantak.message.MachineMeasurementsMessage.battery_current_reading', index=11,
      number=111, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=425,
)


_MACHINECONTROLSMESSAGE = _descriptor.Descriptor(
  name='MachineControlsMessage',
  full_name='anantak.message.MachineControlsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage_output', full_name='anantak.message.MachineControlsMessage.voltage_output', index=0,
      number=200, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_manual_control_state', full_name='anantak.message.MachineControlsMessage.auto_manual_control_state', index=1,
      number=201, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inhibit_control_state', full_name='anantak.message.MachineControlsMessage.inhibit_control_state', index=2,
      number=202, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inhibit2_control_state', full_name='anantak.message.MachineControlsMessage.inhibit2_control_state', index=3,
      number=203, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_mode_control_state', full_name='anantak.message.MachineControlsMessage.speed_mode_control_state', index=4,
      number=204, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_position_output', full_name='anantak.message.MachineControlsMessage.steering_position_output', index=5,
      number=205, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_engaged_output', full_name='anantak.message.MachineControlsMessage.steering_engaged_output', index=6,
      number=206, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignition_control_state', full_name='anantak.message.MachineControlsMessage.ignition_control_state', index=7,
      number=207, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignition_switch_state', full_name='anantak.message.MachineControlsMessage.ignition_switch_state', index=8,
      number=208, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=747,
)


_MACHINESIGNALSMESSAGE = _descriptor.Descriptor(
  name='MachineSignalsMessage',
  full_name='anantak.message.MachineSignalsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_voltage_signal', full_name='anantak.message.MachineSignalsMessage.speed_voltage_signal', index=0,
      number=300, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steering_position_signal', full_name='anantak.message.MachineSignalsMessage.steering_position_signal', index=1,
      number=301, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=838,
)


_MACHINEREADINGSMESSAGE = _descriptor.Descriptor(
  name='MachineReadingsMessage',
  full_name='anantak.message.MachineReadingsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurements', full_name='anantak.message.MachineReadingsMessage.measurements', index=0,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controls', full_name='anantak.message.MachineReadingsMessage.controls', index=1,
      number=1100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signals', full_name='anantak.message.MachineReadingsMessage.signals', index=2,
      number=1200, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=1051,
)

_MACHINEREADINGSMESSAGE.fields_by_name['measurements'].message_type = _MACHINEMEASUREMENTSMESSAGE
_MACHINEREADINGSMESSAGE.fields_by_name['controls'].message_type = _MACHINECONTROLSMESSAGE
_MACHINEREADINGSMESSAGE.fields_by_name['signals'].message_type = _MACHINESIGNALSMESSAGE
DESCRIPTOR.message_types_by_name['MachineMeasurementsMessage'] = _MACHINEMEASUREMENTSMESSAGE
DESCRIPTOR.message_types_by_name['MachineControlsMessage'] = _MACHINECONTROLSMESSAGE
DESCRIPTOR.message_types_by_name['MachineSignalsMessage'] = _MACHINESIGNALSMESSAGE
DESCRIPTOR.message_types_by_name['MachineReadingsMessage'] = _MACHINEREADINGSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MachineMeasurementsMessage = _reflection.GeneratedProtocolMessageType('MachineMeasurementsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MACHINEMEASUREMENTSMESSAGE,
  '__module__' : 'machine_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.MachineMeasurementsMessage)
  })
_sym_db.RegisterMessage(MachineMeasurementsMessage)

MachineControlsMessage = _reflection.GeneratedProtocolMessageType('MachineControlsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MACHINECONTROLSMESSAGE,
  '__module__' : 'machine_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.MachineControlsMessage)
  })
_sym_db.RegisterMessage(MachineControlsMessage)

MachineSignalsMessage = _reflection.GeneratedProtocolMessageType('MachineSignalsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MACHINESIGNALSMESSAGE,
  '__module__' : 'machine_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.MachineSignalsMessage)
  })
_sym_db.RegisterMessage(MachineSignalsMessage)

MachineReadingsMessage = _reflection.GeneratedProtocolMessageType('MachineReadingsMessage', (_message.Message,), {
  'DESCRIPTOR' : _MACHINEREADINGSMESSAGE,
  '__module__' : 'machine_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.MachineReadingsMessage)
  })
_sym_db.RegisterMessage(MachineReadingsMessage)


# @@protoc_insertion_point(module_scope)
