# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programs_setup.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='programs_setup.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14programs_setup.proto\x12\x0f\x61nantak.message\"\xa2\x05\n\rProgramsSetup\x12\x0c\n\x04name\x18\x01 \x02(\t\x12H\n\x10program_settings\x18\x64 \x03(\x0b\x32..anantak.message.ProgramsSetup.ProgramSettings\x1a\xb8\x04\n\x0fProgramSettings\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0c\x63ommand_line\x18\x02 \x01(\t\x12\x13\n\x0bstatus_type\x18\x03 \x01(\t\x12\x19\n\x11startup_direction\x18\x04 \x01(\t\x12\x18\n\x10startup_sequence\x18\x05 \x01(\x05\x12\x13\n\x0b\x63onfig_file\x18\x06 \x01(\t\x12\x1a\n\x12\x63omponent_template\x18\x07 \x01(\t\x12W\n\x0csubscription\x18\x64 \x03(\x0b\x32\x41.anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings\x12W\n\x0bpublication\x18\xc8\x01 \x03(\x0b\x32\x41.anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings\x1a\xa8\x01\n\x12\x43onnectionSettings\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12K\n\x04type\x18\x04 \x01(\x0e\x32=.anantak.message.ProgramsSetup.ProgramSettings.ConnectionType\x12\x14\n\x0cmessage_type\x18\x05 \x01(\t\")\n\x0e\x43onnectionType\x12\n\n\x06STATUS\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01'
)



_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONTYPE = _descriptor.EnumDescriptor(
  name='ConnectionType',
  full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=675,
  serialized_end=716,
)
_sym_db.RegisterEnumDescriptor(_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONTYPE)


_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS = _descriptor.Descriptor(
  name='ConnectionSettings',
  full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings.endpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings.message_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=673,
)

_PROGRAMSSETUP_PROGRAMSETTINGS = _descriptor.Descriptor(
  name='ProgramSettings',
  full_name='anantak.message.ProgramsSetup.ProgramSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.message.ProgramsSetup.ProgramSettings.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command_line', full_name='anantak.message.ProgramsSetup.ProgramSettings.command_line', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_type', full_name='anantak.message.ProgramsSetup.ProgramSettings.status_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startup_direction', full_name='anantak.message.ProgramsSetup.ProgramSettings.startup_direction', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startup_sequence', full_name='anantak.message.ProgramsSetup.ProgramSettings.startup_sequence', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config_file', full_name='anantak.message.ProgramsSetup.ProgramSettings.config_file', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='component_template', full_name='anantak.message.ProgramsSetup.ProgramSettings.component_template', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subscription', full_name='anantak.message.ProgramsSetup.ProgramSettings.subscription', index=7,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publication', full_name='anantak.message.ProgramsSetup.ProgramSettings.publication', index=8,
      number=200, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS, ],
  enum_types=[
    _PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=716,
)

_PROGRAMSSETUP = _descriptor.Descriptor(
  name='ProgramsSetup',
  full_name='anantak.message.ProgramsSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.message.ProgramsSetup.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='program_settings', full_name='anantak.message.ProgramsSetup.program_settings', index=1,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROGRAMSSETUP_PROGRAMSETTINGS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=716,
)

_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS.fields_by_name['type'].enum_type = _PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONTYPE
_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS.containing_type = _PROGRAMSSETUP_PROGRAMSETTINGS
_PROGRAMSSETUP_PROGRAMSETTINGS.fields_by_name['subscription'].message_type = _PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS
_PROGRAMSSETUP_PROGRAMSETTINGS.fields_by_name['publication'].message_type = _PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS
_PROGRAMSSETUP_PROGRAMSETTINGS.containing_type = _PROGRAMSSETUP
_PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONTYPE.containing_type = _PROGRAMSSETUP_PROGRAMSETTINGS
_PROGRAMSSETUP.fields_by_name['program_settings'].message_type = _PROGRAMSSETUP_PROGRAMSETTINGS
DESCRIPTOR.message_types_by_name['ProgramsSetup'] = _PROGRAMSSETUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramsSetup = _reflection.GeneratedProtocolMessageType('ProgramsSetup', (_message.Message,), {

  'ProgramSettings' : _reflection.GeneratedProtocolMessageType('ProgramSettings', (_message.Message,), {

    'ConnectionSettings' : _reflection.GeneratedProtocolMessageType('ConnectionSettings', (_message.Message,), {
      'DESCRIPTOR' : _PROGRAMSSETUP_PROGRAMSETTINGS_CONNECTIONSETTINGS,
      '__module__' : 'programs_setup_pb2'
      # @@protoc_insertion_point(class_scope:anantak.message.ProgramsSetup.ProgramSettings.ConnectionSettings)
      })
    ,
    'DESCRIPTOR' : _PROGRAMSSETUP_PROGRAMSETTINGS,
    '__module__' : 'programs_setup_pb2'
    # @@protoc_insertion_point(class_scope:anantak.message.ProgramsSetup.ProgramSettings)
    })
  ,
  'DESCRIPTOR' : _PROGRAMSSETUP,
  '__module__' : 'programs_setup_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.ProgramsSetup)
  })
_sym_db.RegisterMessage(ProgramsSetup)
_sym_db.RegisterMessage(ProgramsSetup.ProgramSettings)
_sym_db.RegisterMessage(ProgramsSetup.ProgramSettings.ConnectionSettings)


# @@protoc_insertion_point(module_scope)
