# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reporter_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reporter_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x17reporter_messages.proto\x12\x0f\x61nantak.message\"\xc7\x04\n\x0fReporterMessage\x12\x11\n\tunique_id\x18\n \x01(\t\x12\x12\n\nowner_name\x18\x0b \x01(\t\x12\x10\n\x08severity\x18\x0c \x01(\x05\x12\x0f\n\x07message\x18\r \x01(\t\x12\x0e\n\x06\x66ormat\x18\x0e \x01(\t\x12\x19\n\x11last_timestamp_us\x18\x0f \x01(\x03\x12\x13\n\x0bsource_func\x18\x10 \x01(\t\x12\x17\n\x0fsource_filename\x18\x11 \x01(\t\x12\x17\n\x0fsource_line_num\x18\x12 \x01(\x05\x12\x13\n\x0blifespan_ms\x18\x14 \x01(\x05\x12\x1b\n\x13publish_interval_us\x18\x15 \x01(\x03\x12\x0f\n\x07user_id\x18\x1e \x01(\t\x12\x18\n\x10user_description\x18\x1f \x01(\t\x12\x15\n\ruser_category\x18  \x01(\t\x12\x14\n\x0cuser_command\x18! \x01(\t\x12\x11\n\tuser_link\x18\" \x01(\t\x12\x13\n\x0buser_status\x18# \x01(\t\x12\x15\n\ruser_priority\x18$ \x01(\x05\x12\x1a\n\x12report_start_ts_us\x18\x32 \x01(\x03\x12\x18\n\x10report_end_ts_us\x18\x33 \x01(\x03\x12\x19\n\x11report_num_counts\x18\x34 \x01(\x03\x12\x1f\n\x17incremental_start_ts_us\x18\x35 \x01(\x03\x12\x1d\n\x15incremental_end_ts_us\x18\x36 \x01(\x03\x12\x1e\n\x16incremental_num_counts\x18\x37 \x01(\x03\"O\n\x10ReporterDatabase\x12;\n\x11reporter_messages\x18\x01 \x03(\x0b\x32 .anantak.message.ReporterMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REPORTERMESSAGE = _descriptor.Descriptor(
  name='ReporterMessage',
  full_name='anantak.message.ReporterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='anantak.message.ReporterMessage.unique_id', index=0,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_name', full_name='anantak.message.ReporterMessage.owner_name', index=1,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='severity', full_name='anantak.message.ReporterMessage.severity', index=2,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='anantak.message.ReporterMessage.message', index=3,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='anantak.message.ReporterMessage.format', index=4,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_timestamp_us', full_name='anantak.message.ReporterMessage.last_timestamp_us', index=5,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_func', full_name='anantak.message.ReporterMessage.source_func', index=6,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_filename', full_name='anantak.message.ReporterMessage.source_filename', index=7,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_line_num', full_name='anantak.message.ReporterMessage.source_line_num', index=8,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lifespan_ms', full_name='anantak.message.ReporterMessage.lifespan_ms', index=9,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publish_interval_us', full_name='anantak.message.ReporterMessage.publish_interval_us', index=10,
      number=21, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='anantak.message.ReporterMessage.user_id', index=11,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_description', full_name='anantak.message.ReporterMessage.user_description', index=12,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_category', full_name='anantak.message.ReporterMessage.user_category', index=13,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_command', full_name='anantak.message.ReporterMessage.user_command', index=14,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_link', full_name='anantak.message.ReporterMessage.user_link', index=15,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_status', full_name='anantak.message.ReporterMessage.user_status', index=16,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_priority', full_name='anantak.message.ReporterMessage.user_priority', index=17,
      number=36, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='report_start_ts_us', full_name='anantak.message.ReporterMessage.report_start_ts_us', index=18,
      number=50, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='report_end_ts_us', full_name='anantak.message.ReporterMessage.report_end_ts_us', index=19,
      number=51, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='report_num_counts', full_name='anantak.message.ReporterMessage.report_num_counts', index=20,
      number=52, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incremental_start_ts_us', full_name='anantak.message.ReporterMessage.incremental_start_ts_us', index=21,
      number=53, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incremental_end_ts_us', full_name='anantak.message.ReporterMessage.incremental_end_ts_us', index=22,
      number=54, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incremental_num_counts', full_name='anantak.message.ReporterMessage.incremental_num_counts', index=23,
      number=55, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=628,
)


_REPORTERDATABASE = _descriptor.Descriptor(
  name='ReporterDatabase',
  full_name='anantak.message.ReporterDatabase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reporter_messages', full_name='anantak.message.ReporterDatabase.reporter_messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=709,
)

_REPORTERDATABASE.fields_by_name['reporter_messages'].message_type = _REPORTERMESSAGE
DESCRIPTOR.message_types_by_name['ReporterMessage'] = _REPORTERMESSAGE
DESCRIPTOR.message_types_by_name['ReporterDatabase'] = _REPORTERDATABASE

ReporterMessage = _reflection.GeneratedProtocolMessageType('ReporterMessage', (_message.Message,), dict(
  DESCRIPTOR = _REPORTERMESSAGE,
  __module__ = 'reporter_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.ReporterMessage)
  ))
_sym_db.RegisterMessage(ReporterMessage)

ReporterDatabase = _reflection.GeneratedProtocolMessageType('ReporterDatabase', (_message.Message,), dict(
  DESCRIPTOR = _REPORTERDATABASE,
  __module__ = 'reporter_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.ReporterDatabase)
  ))
_sym_db.RegisterMessage(ReporterDatabase)


# @@protoc_insertion_point(module_scope)
