# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status_messages.proto',
  package='anantak.message',
  syntax='proto2',
  serialized_pb=_b('\n\x15status_messages.proto\x12\x0f\x61nantak.message\"!\n\x0bStatusQuery\x12\x12\n\nquery_time\x18\x01 \x02(\x03\"\x89\x01\n\x0bStatusReply\x12\x12\n\nquery_time\x18\x01 \x02(\x03\x12\x12\n\nreply_time\x18\x02 \x02(\x03\x12\x19\n\x11query_reply_delay\x18\x03 \x01(\x03\x12\x0f\n\x07up_time\x18\x04 \x01(\x03\x12\x12\n\nstatus_str\x18\x05 \x01(\t\x12\x12\n\nprocess_id\x18\x06 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STATUSQUERY = _descriptor.Descriptor(
  name='StatusQuery',
  full_name='anantak.message.StatusQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_time', full_name='anantak.message.StatusQuery.query_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=75,
)


_STATUSREPLY = _descriptor.Descriptor(
  name='StatusReply',
  full_name='anantak.message.StatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_time', full_name='anantak.message.StatusReply.query_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reply_time', full_name='anantak.message.StatusReply.reply_time', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query_reply_delay', full_name='anantak.message.StatusReply.query_reply_delay', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='up_time', full_name='anantak.message.StatusReply.up_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_str', full_name='anantak.message.StatusReply.status_str', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='anantak.message.StatusReply.process_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=215,
)

DESCRIPTOR.message_types_by_name['StatusQuery'] = _STATUSQUERY
DESCRIPTOR.message_types_by_name['StatusReply'] = _STATUSREPLY

StatusQuery = _reflection.GeneratedProtocolMessageType('StatusQuery', (_message.Message,), dict(
  DESCRIPTOR = _STATUSQUERY,
  __module__ = 'status_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.StatusQuery)
  ))
_sym_db.RegisterMessage(StatusQuery)

StatusReply = _reflection.GeneratedProtocolMessageType('StatusReply', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREPLY,
  __module__ = 'status_messages_pb2'
  # @@protoc_insertion_point(class_scope:anantak.message.StatusReply)
  ))
_sym_db.RegisterMessage(StatusReply)


# @@protoc_insertion_point(module_scope)
