# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_tracker_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='time_tracker_message.proto',
  package='anantak',
  syntax='proto2',
  serialized_pb=_b('\n\x1atime_tracker_message.proto\x12\x07\x61nantak\"l\n\x11TimeKeeperMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1a\n\x12\x61verage_event_time\x18\n \x02(\x02\x12\x1a\n\x12\x61verage_timer_time\x18\x0b \x02(\x02\x12\x11\n\tcall_rate\x18\x0c \x02(\x02\"[\n\x12TimeTrackerMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x37\n\x13time_keeper_message\x18\n \x03(\x0b\x32\x1a.anantak.TimeKeeperMessage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMEKEEPERMESSAGE = _descriptor.Descriptor(
  name='TimeKeeperMessage',
  full_name='anantak.TimeKeeperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.TimeKeeperMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_event_time', full_name='anantak.TimeKeeperMessage.average_event_time', index=1,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_timer_time', full_name='anantak.TimeKeeperMessage.average_timer_time', index=2,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='call_rate', full_name='anantak.TimeKeeperMessage.call_rate', index=3,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=147,
)


_TIMETRACKERMESSAGE = _descriptor.Descriptor(
  name='TimeTrackerMessage',
  full_name='anantak.TimeTrackerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anantak.TimeTrackerMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_keeper_message', full_name='anantak.TimeTrackerMessage.time_keeper_message', index=1,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=240,
)

_TIMETRACKERMESSAGE.fields_by_name['time_keeper_message'].message_type = _TIMEKEEPERMESSAGE
DESCRIPTOR.message_types_by_name['TimeKeeperMessage'] = _TIMEKEEPERMESSAGE
DESCRIPTOR.message_types_by_name['TimeTrackerMessage'] = _TIMETRACKERMESSAGE

TimeKeeperMessage = _reflection.GeneratedProtocolMessageType('TimeKeeperMessage', (_message.Message,), dict(
  DESCRIPTOR = _TIMEKEEPERMESSAGE,
  __module__ = 'time_tracker_message_pb2'
  # @@protoc_insertion_point(class_scope:anantak.TimeKeeperMessage)
  ))
_sym_db.RegisterMessage(TimeKeeperMessage)

TimeTrackerMessage = _reflection.GeneratedProtocolMessageType('TimeTrackerMessage', (_message.Message,), dict(
  DESCRIPTOR = _TIMETRACKERMESSAGE,
  __module__ = 'time_tracker_message_pb2'
  # @@protoc_insertion_point(class_scope:anantak.TimeTrackerMessage)
  ))
_sym_db.RegisterMessage(TimeTrackerMessage)


# @@protoc_insertion_point(module_scope)
